[metadata]
name = ckanext-fair3r
description = A ckan extension meant to customize fair3r.fr theme and add special views
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Phen-ICS/ckanext-fair3r
author = Nathanaël Debanne
author_email = debannen@igbmc.fr
license = CECILL-B
license_files = LICENSE
classifiers =
            Development Status :: 4 - Beta
            Programming Language :: Python :: 3.7
            Programming Language :: Python :: 3.8
            Programming Language :: Python :: 3.9
            Programming Language :: Python :: 3.10
keywords = CKAN

[options]
packages = find_namespace:
install_requires =
include_package_data = True

[options.entry_points]
ckan.plugins =
             fair3r = ckanext.fair3r.plugin:Fair3RPlugin

babel.extractors =
                 ckan = ckan.lib.extract:extract_ckan

[options.extras_require]

[extract_messages]
keywords = translate isPlural
add_comments = TRANSLATORS:
output_file = ckanext/fair3r/i18n/ckanext-fair3r.pot
width = 80

[init_catalog]
domain = ckanext-fair3r
input_file = ckanext/fair3r/i18n/ckanext-fair3r.pot
output_dir = ckanext/fair3r/i18n

[update_catalog]
domain = ckanext-fair3r
input_file = ckanext/fair3r/i18n/ckanext-fair3r.pot
output_dir = ckanext/fair3r/i18n
previous = true

[compile_catalog]
domain = ckanext-fair3r
directory = ckanext/fair3r/i18n
statistics = true

[tool:pytest]
addopts = --ckan-ini=test.ini
filterwarnings =
        ignore::sqlalchemy.exc.SADeprecationWarning
        ignore::sqlalchemy.exc.SAWarning
        ignore::DeprecationWarning
        ignore::pytest.PytestAssertRewriteWarning
markers =
        ckan_config(key, value): override CKAN config values for a test
